# Generated by Django 5.2.2 on 2026-04-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_portfolioprofile_about_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workexperience",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="privacy_policy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioprofile",
            name="terms_of_service",
            field=models.TextField(blank=True, null=True),
        ),
    ]
