# Generated by Django 5.2.2 on 2026-04-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_terms_of_service_privacy_policy_to_portfolioprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
